---
language: java

branches:
  only:
    - master
    - /^travis/
    - /^v.*/

stages:
  - name: test
  - name: deploy gh-pages
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      install:
        -
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: deploy gh-pages
      install:
        -
      test:
        -
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            branch: master

