---
language: java
jdk: openjdk9

branches:
  only:
    - master
    - /^travis/
    - /^v.*/

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      install: ""
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      install: ""
      test: ""
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            branch: master
    - stage: deploy
      install:
        - ""
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            branch: master
